"""add: Post.private

Revision ID: 6ff4a6169451
Revises: d16751307e7f
Create Date: 2020-09-29 19:28:09.226132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff4a6169451'
down_revision = 'd16751307e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'private')
    # ### end Alembic commands ###
