"""add: Post.slug

Revision ID: c4de5e468202
Revises: 6ff4a6169451
Create Date: 2020-09-30 15:31:57.387956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4de5e468202'
down_revision = '6ff4a6169451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
